// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: fileapi.proto

package proto

import (
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileInformation struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                      `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                     `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mtime         int64                     `protobuf:"varint,4,opt,name=mtime,proto3" json:"mtime,omitempty"`
	MimeType      string                    `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	ExifData      map[string]*_struct.Value `protobuf:"bytes,6,rep,name=exif_data,json=exifData,proto3" json:"exif_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInformation) Reset() {
	*x = FileInformation{}
	mi := &file_fileapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInformation) ProtoMessage() {}

func (x *FileInformation) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInformation.ProtoReflect.Descriptor instead.
func (*FileInformation) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{0}
}

func (x *FileInformation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInformation) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInformation) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInformation) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *FileInformation) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileInformation) GetExifData() map[string]*_struct.Value {
	if x != nil {
		return x.ExifData
	}
	return nil
}

type ImageRepoHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []string               `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	LastId        int64                  `protobuf:"varint,2,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Order         int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRepoHistoryRequest) Reset() {
	*x = ImageRepoHistoryRequest{}
	mi := &file_fileapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRepoHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRepoHistoryRequest) ProtoMessage() {}

func (x *ImageRepoHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRepoHistoryRequest.ProtoReflect.Descriptor instead.
func (*ImageRepoHistoryRequest) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{1}
}

func (x *ImageRepoHistoryRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ImageRepoHistoryRequest) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *ImageRepoHistoryRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ImageRepoHistoryRequest) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *ImageRepoHistoryRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ImageRepoHistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                        // 1:创建, 2:删除, 3:修改
	Etime         int64                  `protobuf:"varint,4,opt,name=etime,proto3" json:"etime,omitempty"`                      // 图片拍摄时间 (Unix 时间戳，毫秒)
	Mtime         int64                  `protobuf:"varint,5,opt,name=mtime,proto3" json:"mtime,omitempty"`                      // 文件修改时间 (Unix 时间戳，毫秒)
	FilePath      string                 `protobuf:"bytes,6,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // 文件路径（兼容旧字段）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRepoHistoryItem) Reset() {
	*x = ImageRepoHistoryItem{}
	mi := &file_fileapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRepoHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRepoHistoryItem) ProtoMessage() {}

func (x *ImageRepoHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRepoHistoryItem.ProtoReflect.Descriptor instead.
func (*ImageRepoHistoryItem) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{2}
}

func (x *ImageRepoHistoryItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageRepoHistoryItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ImageRepoHistoryItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ImageRepoHistoryItem) GetEtime() int64 {
	if x != nil {
		return x.Etime
	}
	return 0
}

func (x *ImageRepoHistoryItem) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *ImageRepoHistoryItem) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type ImageRepoHistoryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Total         int32                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	MaxId         int64                   `protobuf:"varint,2,opt,name=max_id,json=maxId,proto3" json:"max_id,omitempty"`
	Version       string                  `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Items         []*ImageRepoHistoryItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRepoHistoryResponse) Reset() {
	*x = ImageRepoHistoryResponse{}
	mi := &file_fileapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRepoHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRepoHistoryResponse) ProtoMessage() {}

func (x *ImageRepoHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRepoHistoryResponse.ProtoReflect.Descriptor instead.
func (*ImageRepoHistoryResponse) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{3}
}

func (x *ImageRepoHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ImageRepoHistoryResponse) GetMaxId() int64 {
	if x != nil {
		return x.MaxId
	}
	return 0
}

func (x *ImageRepoHistoryResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ImageRepoHistoryResponse) GetItems() []*ImageRepoHistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Prepare file receive request (used in WebRTC)
type PrepareFileReceiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareFileReceiveRequest) Reset() {
	*x = PrepareFileReceiveRequest{}
	mi := &file_fileapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareFileReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareFileReceiveRequest) ProtoMessage() {}

func (x *PrepareFileReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareFileReceiveRequest.ProtoReflect.Descriptor instead.
func (*PrepareFileReceiveRequest) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareFileReceiveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PrepareFileReceiveRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PrepareFileReceiveRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PrepareFileReceiveRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Prepare file receive response
type PrepareFileReceiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareFileReceiveResponse) Reset() {
	*x = PrepareFileReceiveResponse{}
	mi := &file_fileapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareFileReceiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareFileReceiveResponse) ProtoMessage() {}

func (x *PrepareFileReceiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareFileReceiveResponse.ProtoReflect.Descriptor instead.
func (*PrepareFileReceiveResponse) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{5}
}

func (x *PrepareFileReceiveResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Get file info request
type GetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoRequest) Reset() {
	*x = GetFileInfoRequest{}
	mi := &file_fileapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoRequest) ProtoMessage() {}

func (x *GetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileInfoRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// List files request
type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_fileapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{7}
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// List files response
type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInformation     `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_fileapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{8}
}

func (x *ListFilesResponse) GetFiles() []*FileInformation {
	if x != nil {
		return x.Files
	}
	return nil
}

// Get file system version request
type GetFileSystemVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileSystemVersionRequest) Reset() {
	*x = GetFileSystemVersionRequest{}
	mi := &file_fileapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileSystemVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileSystemVersionRequest) ProtoMessage() {}

func (x *GetFileSystemVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileSystemVersionRequest.ProtoReflect.Descriptor instead.
func (*GetFileSystemVersionRequest) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{9}
}

// Get file system version response
type GetFileSystemVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileSystemVersionResponse) Reset() {
	*x = GetFileSystemVersionResponse{}
	mi := &file_fileapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileSystemVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileSystemVersionResponse) ProtoMessage() {}

func (x *GetFileSystemVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileSystemVersionResponse.ProtoReflect.Descriptor instead.
func (*GetFileSystemVersionResponse) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{10}
}

func (x *GetFileSystemVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Get thumbnail request
type GetThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // optional, default 200
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThumbnailRequest) Reset() {
	*x = GetThumbnailRequest{}
	mi := &file_fileapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThumbnailRequest) ProtoMessage() {}

func (x *GetThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThumbnailRequest.ProtoReflect.Descriptor instead.
func (*GetThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{11}
}

func (x *GetThumbnailRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetThumbnailRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Get thumbnail response
type GetThumbnailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // thumbnail ID for data channel
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThumbnailResponse) Reset() {
	*x = GetThumbnailResponse{}
	mi := &file_fileapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThumbnailResponse) ProtoMessage() {}

func (x *GetThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThumbnailResponse.ProtoReflect.Descriptor instead.
func (*GetThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{12}
}

func (x *GetThumbnailResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Play video request
type PlayVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayVideoRequest) Reset() {
	*x = PlayVideoRequest{}
	mi := &file_fileapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayVideoRequest) ProtoMessage() {}

func (x *PlayVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayVideoRequest.ProtoReflect.Descriptor instead.
func (*PlayVideoRequest) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{13}
}

func (x *PlayVideoRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Play video response
type PlayVideoResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	VideoInfo     map[string]*_struct.Value `protobuf:"bytes,3,rep,name=video_info,json=videoInfo,proto3" json:"video_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // optional video information
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayVideoResponse) Reset() {
	*x = PlayVideoResponse{}
	mi := &file_fileapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayVideoResponse) ProtoMessage() {}

func (x *PlayVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayVideoResponse.ProtoReflect.Descriptor instead.
func (*PlayVideoResponse) Descriptor() ([]byte, []int) {
	return file_fileapi_proto_rawDescGZIP(), []int{14}
}

func (x *PlayVideoResponse) GetVideoInfo() map[string]*_struct.Value {
	if x != nil {
		return x.VideoInfo
	}
	return nil
}

var File_fileapi_proto protoreflect.FileDescriptor

const file_fileapi_proto_rawDesc = "" +
	"\n" +
	"\rfileapi.proto\x12\aneutron\x1a\x1cgoogle/protobuf/struct.proto\"\x9d\x02\n" +
	"\x0fFileInformation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x14\n" +
	"\x05mtime\x18\x04 \x01(\x03R\x05mtime\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12C\n" +
	"\texif_data\x18\x06 \x03(\v2&.neutron.FileInformation.ExifDataEntryR\bexifData\x1aS\n" +
	"\rExifDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x17ImageRepoHistoryRequest\x12\x14\n" +
	"\x05types\x18\x01 \x03(\tR\x05types\x12\x17\n" +
	"\alast_id\x18\x02 \x01(\x03R\x06lastId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x05R\x05order\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"\x97\x01\n" +
	"\x14ImageRepoHistoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x14\n" +
	"\x05etime\x18\x04 \x01(\x03R\x05etime\x12\x14\n" +
	"\x05mtime\x18\x05 \x01(\x03R\x05mtime\x12\x1b\n" +
	"\tfile_path\x18\x06 \x01(\tR\bfilePath\"\x96\x01\n" +
	"\x18ImageRepoHistoryResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x15\n" +
	"\x06max_id\x18\x02 \x01(\x03R\x05maxId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x123\n" +
	"\x05items\x18\x04 \x03(\v2\x1d.neutron.ImageRepoHistoryItemR\x05items\"q\n" +
	"\x19PrepareFileReceiveRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"0\n" +
	"\x1aPrepareFileReceiveResponse\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"(\n" +
	"\x12GetFileInfoRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"&\n" +
	"\x10ListFilesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"C\n" +
	"\x11ListFilesResponse\x12.\n" +
	"\x05files\x18\x01 \x03(\v2\x18.neutron.FileInformationR\x05files\"\x1d\n" +
	"\x1bGetFileSystemVersionRequest\"8\n" +
	"\x1cGetFileSystemVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"=\n" +
	"\x13GetThumbnailRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"&\n" +
	"\x14GetThumbnailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x10PlayVideoRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xb3\x01\n" +
	"\x11PlayVideoResponse\x12H\n" +
	"\n" +
	"video_info\x18\x03 \x03(\v2).neutron.PlayVideoResponse.VideoInfoEntryR\tvideoInfo\x1aT\n" +
	"\x0eVideoInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B&Z$github.com/aproton/neutron/pkg/protob\x06proto3"

var (
	file_fileapi_proto_rawDescOnce sync.Once
	file_fileapi_proto_rawDescData []byte
)

func file_fileapi_proto_rawDescGZIP() []byte {
	file_fileapi_proto_rawDescOnce.Do(func() {
		file_fileapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fileapi_proto_rawDesc), len(file_fileapi_proto_rawDesc)))
	})
	return file_fileapi_proto_rawDescData
}

var file_fileapi_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_fileapi_proto_goTypes = []any{
	(*FileInformation)(nil),              // 0: neutron.FileInformation
	(*ImageRepoHistoryRequest)(nil),      // 1: neutron.ImageRepoHistoryRequest
	(*ImageRepoHistoryItem)(nil),         // 2: neutron.ImageRepoHistoryItem
	(*ImageRepoHistoryResponse)(nil),     // 3: neutron.ImageRepoHistoryResponse
	(*PrepareFileReceiveRequest)(nil),    // 4: neutron.PrepareFileReceiveRequest
	(*PrepareFileReceiveResponse)(nil),   // 5: neutron.PrepareFileReceiveResponse
	(*GetFileInfoRequest)(nil),           // 6: neutron.GetFileInfoRequest
	(*ListFilesRequest)(nil),             // 7: neutron.ListFilesRequest
	(*ListFilesResponse)(nil),            // 8: neutron.ListFilesResponse
	(*GetFileSystemVersionRequest)(nil),  // 9: neutron.GetFileSystemVersionRequest
	(*GetFileSystemVersionResponse)(nil), // 10: neutron.GetFileSystemVersionResponse
	(*GetThumbnailRequest)(nil),          // 11: neutron.GetThumbnailRequest
	(*GetThumbnailResponse)(nil),         // 12: neutron.GetThumbnailResponse
	(*PlayVideoRequest)(nil),             // 13: neutron.PlayVideoRequest
	(*PlayVideoResponse)(nil),            // 14: neutron.PlayVideoResponse
	nil,                                  // 15: neutron.FileInformation.ExifDataEntry
	nil,                                  // 16: neutron.PlayVideoResponse.VideoInfoEntry
	(*_struct.Value)(nil),                // 17: google.protobuf.Value
}
var file_fileapi_proto_depIdxs = []int32{
	15, // 0: neutron.FileInformation.exif_data:type_name -> neutron.FileInformation.ExifDataEntry
	2,  // 1: neutron.ImageRepoHistoryResponse.items:type_name -> neutron.ImageRepoHistoryItem
	0,  // 2: neutron.ListFilesResponse.files:type_name -> neutron.FileInformation
	16, // 3: neutron.PlayVideoResponse.video_info:type_name -> neutron.PlayVideoResponse.VideoInfoEntry
	17, // 4: neutron.FileInformation.ExifDataEntry.value:type_name -> google.protobuf.Value
	17, // 5: neutron.PlayVideoResponse.VideoInfoEntry.value:type_name -> google.protobuf.Value
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_fileapi_proto_init() }
func file_fileapi_proto_init() {
	if File_fileapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fileapi_proto_rawDesc), len(file_fileapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fileapi_proto_goTypes,
		DependencyIndexes: file_fileapi_proto_depIdxs,
		MessageInfos:      file_fileapi_proto_msgTypes,
	}.Build()
	File_fileapi_proto = out.File
	file_fileapi_proto_goTypes = nil
	file_fileapi_proto_depIdxs = nil
}
