// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: webrtc.proto

package proto

import (
	_ "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Candidate message for ICE candidates
type Candidate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Candidate        string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid           string                 `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMLineIndex    int32                  `protobuf:"varint,3,opt,name=sdp_m_line_index,json=sdpMLineIndex,proto3" json:"sdp_m_line_index,omitempty"`
	UsernameFragment string                 `protobuf:"bytes,4,opt,name=username_fragment,json=usernameFragment,proto3" json:"username_fragment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_webrtc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_webrtc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_webrtc_proto_rawDescGZIP(), []int{0}
}

func (x *Candidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *Candidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *Candidate) GetSdpMLineIndex() int32 {
	if x != nil {
		return x.SdpMLineIndex
	}
	return 0
}

func (x *Candidate) GetUsernameFragment() string {
	if x != nil {
		return x.UsernameFragment
	}
	return ""
}

// WebRTC signaling messages
type WebRTCOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Candidates    []*Candidate           `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRTCOffer) Reset() {
	*x = WebRTCOffer{}
	mi := &file_webrtc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRTCOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCOffer) ProtoMessage() {}

func (x *WebRTCOffer) ProtoReflect() protoreflect.Message {
	mi := &file_webrtc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCOffer.ProtoReflect.Descriptor instead.
func (*WebRTCOffer) Descriptor() ([]byte, []int) {
	return file_webrtc_proto_rawDescGZIP(), []int{1}
}

func (x *WebRTCOffer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *WebRTCOffer) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type WebRTCAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Candidates    []*Candidate           `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRTCAnswer) Reset() {
	*x = WebRTCAnswer{}
	mi := &file_webrtc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRTCAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCAnswer) ProtoMessage() {}

func (x *WebRTCAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_webrtc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCAnswer.ProtoReflect.Descriptor instead.
func (*WebRTCAnswer) Descriptor() ([]byte, []int) {
	return file_webrtc_proto_rawDescGZIP(), []int{2}
}

func (x *WebRTCAnswer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *WebRTCAnswer) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

// WebRTC file transfer request
type FileTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferRequest) Reset() {
	*x = FileTransferRequest{}
	mi := &file_webrtc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferRequest) ProtoMessage() {}

func (x *FileTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webrtc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferRequest.ProtoReflect.Descriptor instead.
func (*FileTransferRequest) Descriptor() ([]byte, []int) {
	return file_webrtc_proto_rawDescGZIP(), []int{3}
}

func (x *FileTransferRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileTransferRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FileTransferRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileTransferRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileTransferRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// WebRTC file transfer response
type FileTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferResponse) Reset() {
	*x = FileTransferResponse{}
	mi := &file_webrtc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferResponse) ProtoMessage() {}

func (x *FileTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webrtc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferResponse.ProtoReflect.Descriptor instead.
func (*FileTransferResponse) Descriptor() ([]byte, []int) {
	return file_webrtc_proto_rawDescGZIP(), []int{4}
}

func (x *FileTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileTransferResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileTransferResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FileTransferResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Thumbnail request
type ThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MaxSize       int32                  `protobuf:"varint,2,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailRequest) Reset() {
	*x = ThumbnailRequest{}
	mi := &file_webrtc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailRequest) ProtoMessage() {}

func (x *ThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webrtc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailRequest.ProtoReflect.Descriptor instead.
func (*ThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_webrtc_proto_rawDescGZIP(), []int{5}
}

func (x *ThumbnailRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ThumbnailRequest) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

// Thumbnail response
type ThumbnailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailResponse) Reset() {
	*x = ThumbnailResponse{}
	mi := &file_webrtc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailResponse) ProtoMessage() {}

func (x *ThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webrtc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailResponse.ProtoReflect.Descriptor instead.
func (*ThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_webrtc_proto_rawDescGZIP(), []int{6}
}

func (x *ThumbnailResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThumbnailResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ThumbnailResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ThumbnailResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_webrtc_proto protoreflect.FileDescriptor

const file_webrtc_proto_rawDesc = "" +
	"\n" +
	"\fwebrtc.proto\x12\aneutron\x1a\x1cgoogle/protobuf/struct.proto\"\x98\x01\n" +
	"\tCandidate\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x02 \x01(\tR\x06sdpMid\x12'\n" +
	"\x10sdp_m_line_index\x18\x03 \x01(\x05R\rsdpMLineIndex\x12+\n" +
	"\x11username_fragment\x18\x04 \x01(\tR\x10usernameFragment\"S\n" +
	"\vWebRTCOffer\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\x122\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x12.neutron.CandidateR\n" +
	"candidates\"T\n" +
	"\fWebRTCAnswer\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\x122\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x12.neutron.CandidateR\n" +
	"candidates\"\x88\x01\n" +
	"\x13FileTransferRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\"j\n" +
	"\x14FileTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"A\n" +
	"\x10ThumbnailRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bmax_size\x18\x02 \x01(\x05R\amaxSize\"g\n" +
	"\x11ThumbnailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorB(H\x01Z$github.com/aproton/neutron/pkg/protob\x06proto3"

var (
	file_webrtc_proto_rawDescOnce sync.Once
	file_webrtc_proto_rawDescData []byte
)

func file_webrtc_proto_rawDescGZIP() []byte {
	file_webrtc_proto_rawDescOnce.Do(func() {
		file_webrtc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webrtc_proto_rawDesc), len(file_webrtc_proto_rawDesc)))
	})
	return file_webrtc_proto_rawDescData
}

var file_webrtc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_webrtc_proto_goTypes = []any{
	(*Candidate)(nil),            // 0: neutron.Candidate
	(*WebRTCOffer)(nil),          // 1: neutron.WebRTCOffer
	(*WebRTCAnswer)(nil),         // 2: neutron.WebRTCAnswer
	(*FileTransferRequest)(nil),  // 3: neutron.FileTransferRequest
	(*FileTransferResponse)(nil), // 4: neutron.FileTransferResponse
	(*ThumbnailRequest)(nil),     // 5: neutron.ThumbnailRequest
	(*ThumbnailResponse)(nil),    // 6: neutron.ThumbnailResponse
}
var file_webrtc_proto_depIdxs = []int32{
	0, // 0: neutron.WebRTCOffer.candidates:type_name -> neutron.Candidate
	0, // 1: neutron.WebRTCAnswer.candidates:type_name -> neutron.Candidate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_webrtc_proto_init() }
func file_webrtc_proto_init() {
	if File_webrtc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webrtc_proto_rawDesc), len(file_webrtc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webrtc_proto_goTypes,
		DependencyIndexes: file_webrtc_proto_depIdxs,
		MessageInfos:      file_webrtc_proto_msgTypes,
	}.Build()
	File_webrtc_proto = out.File
	file_webrtc_proto_goTypes = nil
	file_webrtc_proto_depIdxs = nil
}
