// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: webrtc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebRTCOfferContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRTCOfferContent) Reset() {
	*x = WebRTCOfferContent{}
	mi := &file_webrtc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRTCOfferContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCOfferContent) ProtoMessage() {}

func (x *WebRTCOfferContent) ProtoReflect() protoreflect.Message {
	mi := &file_webrtc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCOfferContent.ProtoReflect.Descriptor instead.
func (*WebRTCOfferContent) Descriptor() ([]byte, []int) {
	return file_webrtc_proto_rawDescGZIP(), []int{0}
}

func (x *WebRTCOfferContent) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type WebRTCAnswerContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRTCAnswerContent) Reset() {
	*x = WebRTCAnswerContent{}
	mi := &file_webrtc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRTCAnswerContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCAnswerContent) ProtoMessage() {}

func (x *WebRTCAnswerContent) ProtoReflect() protoreflect.Message {
	mi := &file_webrtc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCAnswerContent.ProtoReflect.Descriptor instead.
func (*WebRTCAnswerContent) Descriptor() ([]byte, []int) {
	return file_webrtc_proto_rawDescGZIP(), []int{1}
}

func (x *WebRTCAnswerContent) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type WebRTCAnswerCandidatesContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRTCAnswerCandidatesContent) Reset() {
	*x = WebRTCAnswerCandidatesContent{}
	mi := &file_webrtc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRTCAnswerCandidatesContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCAnswerCandidatesContent) ProtoMessage() {}

func (x *WebRTCAnswerCandidatesContent) ProtoReflect() protoreflect.Message {
	mi := &file_webrtc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCAnswerCandidatesContent.ProtoReflect.Descriptor instead.
func (*WebRTCAnswerCandidatesContent) Descriptor() ([]byte, []int) {
	return file_webrtc_proto_rawDescGZIP(), []int{2}
}

func (x *WebRTCAnswerCandidatesContent) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *WebRTCAnswerCandidatesContent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type WebRTCCandidateContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidate     string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRTCCandidateContent) Reset() {
	*x = WebRTCCandidateContent{}
	mi := &file_webrtc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRTCCandidateContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCCandidateContent) ProtoMessage() {}

func (x *WebRTCCandidateContent) ProtoReflect() protoreflect.Message {
	mi := &file_webrtc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCCandidateContent.ProtoReflect.Descriptor instead.
func (*WebRTCCandidateContent) Descriptor() ([]byte, []int) {
	return file_webrtc_proto_rawDescGZIP(), []int{3}
}

func (x *WebRTCCandidateContent) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

var File_webrtc_proto protoreflect.FileDescriptor

const file_webrtc_proto_rawDesc = "" +
	"\n" +
	"\fwebrtc.proto\x12\aneutron\"&\n" +
	"\x12WebRTCOfferContent\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\"'\n" +
	"\x13WebRTCAnswerContent\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\"E\n" +
	"\x1dWebRTCAnswerCandidatesContent\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"6\n" +
	"\x16WebRTCCandidateContent\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidateB&Z$github.com/aproton/neutron/pkg/protob\x06proto3"

var (
	file_webrtc_proto_rawDescOnce sync.Once
	file_webrtc_proto_rawDescData []byte
)

func file_webrtc_proto_rawDescGZIP() []byte {
	file_webrtc_proto_rawDescOnce.Do(func() {
		file_webrtc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webrtc_proto_rawDesc), len(file_webrtc_proto_rawDesc)))
	})
	return file_webrtc_proto_rawDescData
}

var file_webrtc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_webrtc_proto_goTypes = []any{
	(*WebRTCOfferContent)(nil),            // 0: neutron.WebRTCOfferContent
	(*WebRTCAnswerContent)(nil),           // 1: neutron.WebRTCAnswerContent
	(*WebRTCAnswerCandidatesContent)(nil), // 2: neutron.WebRTCAnswerCandidatesContent
	(*WebRTCCandidateContent)(nil),        // 3: neutron.WebRTCCandidateContent
}
var file_webrtc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_webrtc_proto_init() }
func file_webrtc_proto_init() {
	if File_webrtc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webrtc_proto_rawDesc), len(file_webrtc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webrtc_proto_goTypes,
		DependencyIndexes: file_webrtc_proto_depIdxs,
		MessageInfos:      file_webrtc_proto_msgTypes,
	}.Build()
	File_webrtc_proto = out.File
	file_webrtc_proto_goTypes = nil
	file_webrtc_proto_depIdxs = nil
}
